export default {
  SET_SEARCH: "SET_SEARCH",
  RESET_SEARCH: "RESET_SEARCH",
  BUS_SELECT: "BUS_SELECT",
  BOOKING_INFO: "BOOKING_INFO",
  SET_FARE: "SET_FARE",
  SET_NAME: "SET_NAME",
  SET_EMAIL: "SET_EMAIL",
  SET_GENDER: "SET_GENDER",
  SET_MOBILE: "SET_MOBILE",
  SET_AGE: "SET_AGE",
  SET_SEATS: "SET_SEATS",
  SET_PASSENGER_DETAILS: "SET_PASSENGER_DETAILS",
  SET_BUS_SEARCH_DATA: "SET_BUS_SEARCH_DATA",
  SET_LOADING: "SET_LOADING",
  SET_USER_INFO: "SET_USER_INFO",
  SET_BOARDING_POINT: "SET_BOARDING_POINT"
};
